digitize:
  image: icr.io/ai-services-cicd/digitize-service:v0.0.50
  log_level: "INFO"
  database: "digitize_metadata"
  numShards: 1
  # @generate:password length=32, special=false
  dbEncryptionKey: ""
  resources:
    requests:
      cpu: "16"
      memory: "50Gi"
    limits:
      cpu: "16"
      memory: "50Gi"

digitizeUi:
  image: icr.io/ai-services-cicd/digitize-ui:v0.0.31
  resources:
    requests:
      cpu: "50m"
      memory: "512Mi"
    limits:
      cpu: "50m"
      memory: "512Mi"

postgres:
  image: icr.io/ai-services-cicd/postgres:18-5
  storage: 5Gi
  # @generate:password
  password: ""

embedding:
  model:
    name: ""

llm:
  model:
    name: ""
  apiKey: ""
