# build stage
FROM registry.access.redhat.com/ubi9/nodejs-22 AS build

USER 1001
WORKDIR /app
COPY --chown=1001:0 package.json package-lock.json ./
RUN npm ci

COPY --chown=1001:0 . .
RUN npm run build


# runtime stage
FROM registry.access.redhat.com/ubi9/nginx-126:9.7

COPY nginx.conf.tmpl /etc/nginx/nginx.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
