ui:
  port: ""
  image: icr.io/ai-services-cicd/chatbot-ui:v0.0.39

backend:
  port: ""
  image: icr.io/ai-services-cicd/chatbot-service:v0.0.16
  log_level: "INFO"
  chatbot:
    searchMode: "hybrid"
    numChunksPostReranker: 3
    rerank: true
