# build stage
FROM registry.access.redhat.com/ubi9/nodejs-22 AS build

USER 1001
WORKDIR /app
COPY --chown=1001:0 package.json package-lock.json* ./
RUN npm ci

COPY --chown=1001:0 . .
RUN npm run build


# runtime stage
FROM registry.access.redhat.com/ubi9/nginx-126:9.8

USER root
RUN dnf update -y --disablerepo='*' --enablerepo='ubi-9-*' && dnf clean all
USER 1001

COPY nginx.conf.tmpl /etc/nginx/nginx.conf.tmpl
COPY --chmod=755 entrypoint.sh /entrypoint.sh

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 4101

CMD ["/bin/bash", "/entrypoint.sh"]
