ui:
  port: ""
  image: icr.io/ai-services-cicd/catalog-ui:v0.0.29

backend:
  port: ""
  image: icr.io/ai-services-cicd/ai-services:v0.0.128
  runtime: ""
  adminPasswordHash: ""
  podman:
    uri: "/run/podman/podman.sock"
    authFileContent: ""

db:
  port: ""
  image: icr.io/ai-services-cicd/postgres:18-3
  user: "admin"
  database: "ai_services"
  password: ""
  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "1Gi"

caddy:
  image: icr.io/ai-services-cicd/caddy:v2.11.4-0
  adminPort: ""
  # @description HTTPS port for caddy. Set by configure command via --https-port flag.
  httpsPort: ""
