summarize:
  port: ""
  image: icr.io/ai-services-cicd/summarize-service:v0.0.11
  log_level: "INFO"
  database: "summarize_metadata"

postgres:
  image: icr.io/ai-services-cicd/postgres:18-2
  username: "postgres"
  # @generate:password
  password: ""

# Made with Bob
