FROM icr.io/ai-services-cicd/service-base:v0.0.37

WORKDIR /opt/services/digitize

ENV PYTHONPATH=/opt/services

COPY common /opt/services/common
COPY digitize/ .

# Uncomment when you have digitize specific requirements.txt
# RUN source /var/venv/bin/activate && pip install -r requirements.txt && pip cache purge

CMD ["/var/venv/bin/python", "-m", "uvicorn", "app:app", \
     "--host", "0.0.0.0", "--port", "4000", \
     "--loop", "uvloop", "--http", "httptools"]
