digitize:
  image: icr.io/ai-services-cicd/digitize-service:v0.0.33
  log_level: "INFO"
  database: "digitize_metadata"

digitizeUi:
  image: icr.io/ai-services-cicd/digitize-ui:v0.0.27

postgres:
  image: icr.io/ai-services-cicd/postgres:18-4
  username: "postgres"
  # @generate:password
  password: ""
