digitize:
  port: ""
  image: icr.io/ai-services-cicd/digitize-service:v0.0.9
  log_level: "INFO"
  database: "digitize_metadata"

digitizeUi:
  port: ""
  image: icr.io/ai-services-cicd/digitize-ui:v0.0.20

postgres:
  image: icr.io/ai-services-cicd/postgres:18-2
  password: "Aiservicesdb@1234"
