apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "backend"
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
spec:
  port:
    targetPort: 5000
  to:
    kind: Service
    name: "backend"
