{{- if not (lookup "v1" "PersistentVolumeClaim" .Release.Namespace "cache") -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "cache"
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "4Gi"
{{- end -}}
