apiVersion: template.openshift.io/v1
kind: TemplateInstance
metadata:
  name: vllm-cpu-runtime
spec:
  template:
    metadata:
      name: vllm-cpu-runtime-template
      namespace: redhat-ods-applications
