---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opensearch-role
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
rules:
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  resourceNames: ["nonroot-v2"]
  verbs: ["use"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opensearch-role-binding
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
subjects:
- kind: ServiceAccount
  name: opensearch-sa
roleRef:
  kind: Role
  name: opensearch-role
  apiGroup: rbac.authorization.k8s.io
