apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: spyre
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
  annotations:
    opendatahub.io/apiProtocol: REST
spec:
  annotations:
    opendatahub.io/kserve-runtime: vllm
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  containers:
  - args:
    - --model=/mnt/models
    - --port=8000
    - --served-model-name={{ "{{.Name}}" }}
    env:
    - name: HF_HOME
      value: /tmp/hf_home
    image: {{ .Values.instruct.image }}
    name: kserve-container
    ports:
    - containerPort: 8000
      protocol: TCP
    volumeMounts:
    - mountPath: /dev/shm
      name: shm
  multiModel: false
  supportedModelFormats:
  - autoSelect: true
    name: vLLM
  volumes:
  - emptyDir:
      medium: Memory
      sizeLimit: 2Gi
    name: shm
