FROM icr.io/ai-services-cicd/services-common:v0.0.3

WORKDIR /opt/services/similarity

ENV PYTHONPATH=/opt/services

COPY requirements.txt .
RUN source /var/venv/bin/activate && pip install -r requirements.txt && pip cache purge

COPY . .

CMD ["/var/venv/bin/python", "-m", "uvicorn", "app:app", \
     "--host", "0.0.0.0", "--port", "7000", \
     "--loop", "uvloop", "--http", "httptools"]
