name: Digitize UI
on:
  push:
    paths:
      - 'ui/digitize/**'
    branches:
      - main
  pull_request:
    paths:
      - 'ui/digitize/**'
      - .github/workflows/digitize-ui-image.yml
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  ICR_REGISTRY: icr.io
  ICR_NAMESPACE: ai-services-cicd

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: ui/digitize/package-lock.json

      - name: Install dependencies
        working-directory: ui/digitize
        run: npm ci

      - name: Run linter
        working-directory: ui/digitize
        run: npm run lint

  build-publish-image:
    name: Build and Publish Image
    needs: [lint]
    runs-on: ubuntu-24.04-ppc64le

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build digitize-ui image
        working-directory: ui/digitize
        run: |
          make build REGISTRY=${{ env.ICR_REGISTRY }}/${{ env.ICR_NAMESPACE }}

      - name: Publish digitize-ui image
        working-directory: ui/digitize
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          make push \
            REGISTRY=${{ env.ICR_REGISTRY }}/${{ env.ICR_NAMESPACE }} \
            REGISTRY_USER=${{ secrets.ICR_USERNAME }} \
            REGISTRY_PASSWORD=${{ secrets.ICR_APIKEY }}

  scan:
    uses: ./.github/workflows/scanner.yml
    with:
      path: 'ui/digitize'
      image: 'digitize-ui'

 # Made with Bob