name: Postgres
on:
  push:
    paths:
      - 'images/postgres/**'
    branches:
      - main
  pull_request:
    paths:
      - 'images/postgres/**'
      - .github/workflows/postgres-image.yml
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  ICR_REGISTRY: icr.io
  ICR_NAMESPACE: ai-services-cicd

jobs:
  build-publish-image:
    name: Build and Publish Image
    runs-on: ubuntu-24.04-ppc64le

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Build postgres image
        working-directory: images/postgres
        run: |
          make build REGISTRY=${{ env.ICR_REGISTRY }}/${{ env.ICR_NAMESPACE }}

      - name: Publish postgres image
        working-directory: images/postgres
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          make push REGISTRY=${{ env.ICR_REGISTRY }}/${{ env.ICR_NAMESPACE }} REGISTRY_USER=${{ secrets.ICR_USERNAME }} REGISTRY_PASSWORD=${{ secrets.ICR_APIKEY }}
  
  scan:
    uses: ./.github/workflows/scanner.yml
    with:
      path: 'images/postgres'
      image: 'postgres'

# Made with Bob
